services:
    nginx:
        container_name: "caminodeldev-nginx"
        image: nginx:1.20-alpine
        command: nginx -g "daemon off;"
        depends_on:
            - php
        ports:
            - 10.0.0.2:29410:80
        volumes:
            - ../app:/app
            - ./nginx/nginx-api.conf:/etc/nginx/conf.d/default.conf
        networks:
            caminodeldev-net:
                ipv4_address: "10.2.0.10"
    php:
        container_name: "caminodeldev-php"
        image: yiisoftware/yii2-php:8.4-fpm
        depends_on:
            - mysql
        ports:
            - 10.0.0.2:29420:9000
        volumes:
            - ../app:/app
        networks:
            caminodeldev-net:
                ipv4_address: "10.2.0.11"
    mysql:
        container_name: "caminodeldev-mysql"
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - 10.0.0.2:29430:3306
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: caminodeldev
            MYSQL_USER: msdev
            MYSQL_PASSWORD: dev123
        networks:
            caminodeldev-net:
                ipv4_address: "10.2.0.12"

networks:
    caminodeldev-net:
        name: "caminodeldev-net"
        driver: bridge
        ipam: 
            config:
                - subnet: "10.2.0.0/24"